name: nesy_causal_p
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blessed=1.20.0=py38hecd8cb5_0
  - bottleneck=1.3.7=py38h7b7cdfe_0
  - bpython=0.24=py38h50d1736_2
  - brotli=1.0.9=h6c40b1e_8
  - brotli-bin=1.0.9=h6c40b1e_8
  - brotli-python=1.0.9=py38hcec6c5f_8
  - ca-certificates=2024.11.26=hecd8cb5_0
  - certifi=2024.8.30=py38hecd8cb5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - curtsies=0.4.1=pyhd8ed1ab_0
  - cwcwidth=0.1.9=py38hae2e43d_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - farama-notifications=0.0.4=py38hecd8cb5_0
  - filelock=3.13.1=py38hecd8cb5_0
  - freetype=2.12.1=hd8bbffd_0
  - gmp=6.2.1=he9d5cce_3
  - gmpy2=2.1.2=py38hd5de756_0
  - greenlet=3.0.1=py38hcec6c5f_0
  - idna=3.7=py38hecd8cb5_0
  - imageio=2.34.1=pyh4b66e23_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38hecd8cb5_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipython=8.12.0=pyhd1c38e8_0
  - jax-jumpy=1.0.0=py38hecd8cb5_0
  - jedi=0.18.1=py38hecd8cb5_1
  - jinja2=3.1.4=py38hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libbrotlicommon=1.0.9=h6c40b1e_8
  - libbrotlidec=1.0.9=h6c40b1e_8
  - libbrotlienc=1.0.9=h6c40b1e_8
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_1
  - libfaiss=1.7.4=ha5a8b8e_0_cpu
  - libffi=3.4.4=hecd8cb5_1
  - libjpeg-turbo=2.0.0=hca72f7f_0
  - libpng=1.6.39=h6c40b1e_0
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp-base=1.3.2=h6c40b1e_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=2.1.3=py38h6c40b1e_0
  - matplotlib-base=3.7.2=py38hee32256_0
  - matplotlib-inline=0.1.6=py38hecd8cb5_0
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py38h9ed2024_0
  - mkl_fft=1.3.1=py38h4ab4a9b_0
  - mkl_random=1.2.2=py38hb2f4e1b_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpld3=0.5.9=py38hecd8cb5_0
  - mpmath=1.3.0=py38hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - networkx=3.1=py38hecd8cb5_0
  - numexpr=2.8.4=py38he696674_0
  - numpy-base=1.24.3=py38h9cd3388_0
  - openjpeg=2.4.0=h66ea3da_0
  - openssl=3.0.15=h46256e1_0
  - packaging=24.1=py38hecd8cb5_0
  - pandas=2.0.3=py38h3ea8b11_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.3.0=py38h6c40b1e_0
  - pip=24.0=py38hecd8cb5_0
  - prompt-toolkit=3.0.43=py38hecd8cb5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38hecd8cb5_1
  - pysocks=1.7.1=py38_1
  - python=3.8.19=h5ee71fb_0
  - python-dateutil=2.9.0post0=py38hecd8cb5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0.1=py38h6c40b1e_0
  - readline=8.2=hca72f7f_0
  - requests=2.32.2=py38hecd8cb5_0
  - setuptools=69.5.1=py38hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py38hecd8cb5_0
  - tk=8.6.14=h4d00af3_0
  - traitlets=5.14.3=py38hecd8cb5_0
  - typing-extensions=4.11.0=py38hecd8cb5_0
  - typing_extensions=4.11.0=py38hecd8cb5_0
  - unicodedata2=15.1.0=py38h6c40b1e_0
  - urllib3=2.2.1=py38hecd8cb5_0
  - urwid=2.1.2=py38haf1e3a3_0
  - watchdog=4.0.1=py38h3333b6a_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py38hecd8cb5_0
  - xz=5.4.6=h6c40b1e_1
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.5=hc035e20_2
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - ace-tools==0.0
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argparse==1.4.0
      - astunparse==1.6.3
      - attrdict==2.0.1
      - bitsandbytes==0.42.0
      - cachetools==5.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorlog==6.9.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.1.2
      - debugpy==1.8.14
      - deepproblog==2.0.6
      - deepseek-vl==1.0.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.1
      - faiss-cpu==1.8.0.post1
      - fastapi==0.115.13
      - ffmpy==0.5.0
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.32.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - grad-cam==1.5.2
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.65.4
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h11==0.14.0
      - h5py==3.11.0
      - hf-xet==1.1.4
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.33.0
      - importlib-metadata==8.2.0
      - jax==0.4.13
      - joblib==1.4.2
      - keras==2.12.0
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.9
      - lark==1.1.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - numpy==1.24.4
      - nvidia-ml-py==12.555.43
      - oauthlib==3.2.2
      - openai==1.35.10
      - opencv-python==4.8.0.74
      - opt-einsum==3.3.0
      - orjson==3.10.15
      - platformdirs==4.2.2
      - problog==2.2.7
      - protobuf==4.25.4
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pyparsing==3.1.2
      - pysdd==1.0.5
      - python-multipart==0.0.20
      - pytz==2024.2
      - pywavelets==1.4.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9
      - rtpt==0.0.4
      - ruff==0.12.0
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - stable-baselines3==2.4.0
      - starlette==0.44.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.17
      - tokenizers==0.20.3
      - tomlkit==0.12.0
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.4
      - transformers==4.46.3
      - ttach==0.0.3
      - typer==0.16.0
      - tzdata==2024.2
      - uvicorn==0.33.0
      - wandb==0.17.5
      - websockets==12.0
      - werkzeug==3.0.3
      - wrapt==1.14.1
      - zipp==3.19.2
prefix: /Users/jing/opt/anaconda3/envs/nesy_causal_p
