# Multiple intervention scenarios
video:
  width: 500
  height: 400
  num_frames: 100
  fps: 30

objects:
  left_objects: 6
  right_objects: 6
  radius: 16
  velocity: 2

colors:
  default_colors:
    - [100, 150, 255]
    - [255, 150, 100]
    - [150, 255, 100]
    - [255, 100, 150]
    - [150, 100, 255]
    - [100, 255, 150]
    - [200, 200, 100]
    - [150, 150, 255]
    - [100, 200, 200]
    - [200, 150, 150]
  fixed_colors: {}
  background: [0, 0, 0]

movement:
  patterns:
    left:
      direction: down
      velocity: 2
    right:
      direction: up
      velocity: 2

interventions:
  enabled: true
  type: reverse_movement
  # Intervene on multiple objects from each side
  target_indices:
    left: [0, 2, 4]    # Objects 1, 3, 5 (0-indexed)
    right: [1, 3, 5]   # Objects 2, 4, 6 (0-indexed)

rendering:
  show_labels: true
  antialias: true
  dividing_line: true